// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7wQ7Y16YF9RCnesYfdL0ZHD9qqXecnY',
    appId: '1:476540604651:web:4173eae004aae61387eeae',
    messagingSenderId: '476540604651',
    projectId: 'sportverse-ai',
    authDomain: 'sportverse-ai.firebaseapp.com',
    storageBucket: 'sportverse-ai.firebasestorage.app',
    measurementId: 'G-G85WFV4QC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fZHh2vtA-EfoQ5MgIYewXdiOkMLv9v4',
    appId: '1:476540604651:android:e7feb16feccff0d387eeae',
    messagingSenderId: '476540604651',
    projectId: 'sportverse-ai',
    storageBucket: 'sportverse-ai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgYdi8D_xwswrzvUEFHTZiLTgPYwppno',
    appId: '1:476540604651:ios:7fe2aa18a0b704cb87eeae',
    messagingSenderId: '476540604651',
    projectId: 'sportverse-ai',
    storageBucket: 'sportverse-ai.firebasestorage.app',
    androidClientId: '476540604651-kd45r04vhotk1lc39sdnls3khhu75o98.apps.googleusercontent.com',
    iosClientId: '476540604651-2ue95e0034os637mmco7a2ohapn02l64.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportverse',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgYdi8D_xwswrzvUEFHTZiLTgPYwppno',
    appId: '1:476540604651:ios:7fe2aa18a0b704cb87eeae',
    messagingSenderId: '476540604651',
    projectId: 'sportverse-ai',
    storageBucket: 'sportverse-ai.firebasestorage.app',
    androidClientId: '476540604651-kd45r04vhotk1lc39sdnls3khhu75o98.apps.googleusercontent.com',
    iosClientId: '476540604651-2ue95e0034os637mmco7a2ohapn02l64.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo7wQ7Y16YF9RCnesYfdL0ZHD9qqXecnY',
    appId: '1:476540604651:web:9cbac8ca1023825187eeae',
    messagingSenderId: '476540604651',
    projectId: 'sportverse-ai',
    authDomain: 'sportverse-ai.firebaseapp.com',
    storageBucket: 'sportverse-ai.firebasestorage.app',
    measurementId: 'G-7D5S1C8HEY',
  );
}
